// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    1: typeof import('./components/organisations/new/1.vue')['default']
    2: typeof import('./components/organisations/new/2.vue')['default']
    AllProject: typeof import('./components/overview/all-project.vue')['default']
    AppDetails: typeof import('./components/new-project/app-details.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Details: typeof import('./components/create-app/details.vue')['default']
    Details2: typeof import('./components/organisations/new/2vue/details2.vue')['default']
    EmptyProject: typeof import('./components/overview/empty-project.vue')['default']
    IconsComponent: typeof import('./components/icons-component.vue')['default']
    ImportRepo: typeof import('./components/create-app/import-repo.vue')['default']
    Interface: typeof import('./components/organisations/interface.ts')['default']
    ListOrgs: typeof import('./components/organisations/list-orgs.vue')['default']
    ListOrgsTemp: typeof import('./components/organisations/list-orgs-temp.vue')['default']
    Loading: typeof import('./components/base/loading.vue')['default']
    LoadingSkeleton: typeof import('./components/organisations/loadingSkeleton.vue')['default']
    NewWorkspace: typeof import('./components/home/new-workspace.vue')['default']
    Repo2: typeof import('./components/organisations/new/2vue/repo2.vue')['default']
    Setup1: typeof import('./components/setup-app/setup-1.vue')['default']
    Setup2: typeof import('./components/setup-app/setup-2.vue')['default']
  }
}

export { }
