// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Details: typeof import('./components/create-app/details.vue')['default']
    IconsComponent: typeof import('./components/icons-component.vue')['default']
    ImportRepo: typeof import('./components/create-app/import-repo.vue')['default']
    MdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    MdiBellOutline: typeof import('~icons/mdi/bell-outline')['default']
    MdiEmailOutline: typeof import('~icons/mdi/email-outline')['default']
    MdiHomeOutline: typeof import('~icons/mdi/home-outline')['default']
    MdiLink: typeof import('~icons/mdi/link')['default']
    MdiMagnify: typeof import('~icons/mdi/magnify')['default']
    MdiPencil: typeof import('~icons/mdi/pencil')['default']
  }
}

export { }
