// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    1: typeof import('./components/organisations/new/1.vue')['default']
    2: typeof import('./components/organisations/new/2.vue')['default']
    AllProject: typeof import('./components/overview/all-project.vue')['default']
    AppDetails: typeof import('./components/new-project/app-details.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Details: typeof import('./components/create-app/details.vue')['default']
    Details2: typeof import('./components/organisations/new/2vue/details2.vue')['default']
    EmptyProject: typeof import('./components/overview/empty-project.vue')['default']
    IconsComponent: typeof import('./components/icons-component.vue')['default']
    ImportRepo: typeof import('./components/create-app/import-repo.vue')['default']
    Interface: typeof import('./components/organisations/interface.ts')['default']
    ListOrgs: typeof import('./components/organisations/list-orgs.vue')['default']
    ListOrgsTemp: typeof import('./components/organisations/list-orgs-temp.vue')['default']
    Loading: typeof import('./components/base/loading.vue')['default']
    LoadingSkeleton: typeof import('./components/organisations/loadingSkeleton.vue')['default']
    MdiAccountGroupOutline: typeof import('~icons/mdi/account-group-outline')['default']
    MdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    MdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    MdiBellOutline: typeof import('~icons/mdi/bell-outline')['default']
    MdiBitbucket: typeof import('~icons/mdi/bitbucket')['default']
    MdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    MdiEmail: typeof import('~icons/mdi/email')['default']
    MdiEmailOutline: typeof import('~icons/mdi/email-outline')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiGitlab: typeof import('~icons/mdi/gitlab')['default']
    MdiLink: typeof import('~icons/mdi/link')['default']
    MdiMagnify: typeof import('~icons/mdi/magnify')['default']
    MdiOpenInNew: typeof import('~icons/mdi/open-in-new')['default']
    MdiPencil: typeof import('~icons/mdi/pencil')['default']
    MdiPlus: typeof import('~icons/mdi/plus')['default']
    NewWorkspace: typeof import('./components/home/new-workspace.vue')['default']
    Repo2: typeof import('./components/organisations/new/2vue/repo2.vue')['default']
    Setup1: typeof import('./components/setup-app/setup-1.vue')['default']
    Setup2: typeof import('./components/setup-app/setup-2.vue')['default']
  }
}

export { }
